export const SERVICES = [
  {
    id: "01",
    title: "WEB DEVELOPMENT",
    short: "Websites",
    desc: "Blazing-fast marketing sites & platforms. Next.js, headless CMS, edge rendering, 95+ Lighthouse.",
    tags: ["Next.js", "React", "Performance"],
    accent: "#D4FF3F",
    preview: "code",
  },
  {
    id: "02",
    title: "WEB APPLICATIONS",
    short: "Apps",
    desc: "Dashboards, SaaS, portals & internal tools. Postgres, auth, realtime, roles, billing.",
    tags: ["PostgreSQL", "Drizzle", "Auth"],
    accent: "#4DE3FF",
    preview: "app",
  },
  {
    id: "03",
    title: "UI / UX DESIGN",
    short: "Design",
    desc: "Research, wireframes, design systems & prototypes that convert visitors into customers.",
    tags: ["Figma", "Design Systems", "Motion"],
    accent: "#FF7AD9",
    preview: "design",
  },
  {
    id: "04",
    title: "E-COMMERCE",
    short: "Commerce",
    desc: "Headless storefronts with Stripe, inventory, CMS & CRO built-in. Built to sell.",
    tags: ["Stripe", "Headless", "CRO"],
    accent: "#FFB224",
    preview: "shop",
  },
  {
    id: "05",
    title: "DIGITAL EXPERIENCES",
    short: "3D / WebGL",
    desc: "Three.js, WebGL shaders, scroll cinema & interactive storytelling that people remember.",
    tags: ["Three.js", "GSAP", "Shaders"],
    accent: "#7C5CFF",
    preview: "3d",
  },
  {
    id: "06",
    title: "SEO & GROWTH",
    short: "Growth",
    desc: "Technical SEO, analytics, A/B testing & content engines that compound traffic.",
    tags: ["SEO", "Analytics", "Content"],
    accent: "#8AFF80",
    preview: "growth",
  },
];

export const PROCESS = [
  {
    id: "01",
    name: "DISCOVER",
    desc: "Workshops, audits, analytics & stakeholder interviews. We find the real problem before we design anything.",
    deliverables: ["Discovery workshop", "Tech audit", "User insights"],
    color: "#D4FF3F",
  },
  {
    id: "02",
    name: "CONCEPT",
    desc: "Information architecture, creative direction, motion language and prototype of the core journey.",
    deliverables: ["Sitemap", "Creative concept", "Clickable prototype"],
    color: "#4DE3FF",
  },
  {
    id: "03",
    name: "DESIGN",
    desc: "High-fidelity UI, design system, 3D & motion exploration. Every pixel earns its place.",
    deliverables: ["UI kit", "Design system", "Motion specs"],
    color: "#FF7AD9",
  },
  {
    id: "04",
    name: "DEVELOP",
    desc: "Clean code, CMS, integrations, animations & 3D. Reviewed, tested, performance-budgeted.",
    deliverables: ["Frontend + Backend", "CMS", "QA & perf pass"],
    color: "#7C5CFF",
  },
  {
    id: "05",
    name: "LAUNCH",
    desc: "Deploy, monitor, measure & iterate. SEO, analytics and growth loops from day one.",
    deliverables: ["Deploy & SSL", "Analytics", "30-day support"],
    color: "#FFB224",
  },
];

export const TECH_STACK = [
  "Next.js",
  "React",
  "TypeScript",
  "Three.js",
  "WebGL",
  "GSAP",
  "PostgreSQL",
  "Drizzle ORM",
  "Node.js",
  "PHP",
  "MySQL",
  "WordPress",
  "Tailwind",
  "Vercel",
  "Stripe",
  "Figma",
];

export const FALLBACK_PROJECTS = [
  {
    title: "NOVA — Fintech Experience",
    slug: "nova-fintech",
    category: "Web Application",
    tagline: "A realtime banking dashboard that feels like a game.",
    description:
      "Nova needed to turn dense financial data into something humans actually enjoy. We designed a dark, cinematic dashboard with live charts, animated onboarding and a design system that scales to 40+ screens.",
    challenge:
      "Legacy dashboard had 68% drop-off during onboarding. Data was overwhelming, mobile was broken, and brand trust was low.",
    idea: "Treat money like a story — balances, goals and insights as chapters with motion guiding the eye.",
    design:
      "Dark premium UI, lime accents, custom chart language, glass cards and micro-interactions on every action.",
    development:
      "Next.js + Postgres + Drizzle, realtime websockets, role-based access, edge caching for sub-second loads.",
    results:
      "Onboarding completion +142%, NPS 31 → 67, page load 4.2s → 0.9s. Featured in two fintech design galleries.",
    thumbnail: "",
    heroImage: "",
    gallery: [],
    technologies: ["Next.js", "PostgreSQL", "Three.js", "Tailwind"],
    client: "Nova Financial",
    year: "2026",
    status: "published",
    featured: true,
    color: "#D4FF3F",
    stats: [
      { label: "Onboarding lift", value: "+142%" },
      { label: "Load time", value: "0.9s" },
      { label: "NPS", value: "67" },
    ],
    timeline: "8 weeks",
  },
  {
    title: "ATELIER NOIR — E-Commerce",
    slug: "atelier-noir",
    category: "E-Commerce",
    tagline: "Luxury fashion storefront with editorial soul.",
    description:
      "A Parisian fashion house wanted e-commerce that feels like a magazine. Horizontal lookbooks, 3D fabric views, instant checkout.",
    challenge:
      "Bounce rate 74% on mobile. Product imagery flat. Checkout took 6 steps and killed conversion.",
    idea: "Merge editorial storytelling with commerce — every collection is a scrollable film.",
    design: "Oversized serif type, full-bleed imagery, hover distortions, custom cursor with quick-view.",
    development: "Headless Shopify + Next.js, Stripe, Algolia search, ISR for 2k SKUs with 0.7s LCP.",
    results: "Conversion 1.1% → 3.4%, AOV +28%, mobile revenue +210% in 90 days.",
    thumbnail: "",
    heroImage: "",
    gallery: [],
    technologies: ["Next.js", "Stripe", "GSAP", "Shopify"],
    client: "Atelier Noir",
    year: "2025",
    status: "published",
    featured: true,
    color: "#FF7AD9",
    stats: [
      { label: "Conversion", value: "3.4%" },
      { label: "AOV lift", value: "+28%" },
      { label: "Mobile revenue", value: "+210%" },
    ],
    timeline: "10 weeks",
  },
  {
    title: "ORBITAL — SaaS Platform",
    slug: "orbital-saas",
    category: "SaaS Platform",
    tagline: "Mission control for remote teams.",
    description:
      "Orbital is a project OS for distributed teams. We built marketing site + app with realtime collab, docs and analytics.",
    challenge: "Churn 9% monthly. Users couldn't find features. Marketing site didn't explain product.",
    idea: "One visual language from landing to app — learn it once, use everywhere.",
    design: "Modular card UI, command palette, keyboard-first, dark/light adaptive system.",
    development: "Multi-tenant Postgres, Drizzle, realtime CRDT, billing with Stripe, full test coverage.",
    results: "Activation +86%, churn 9% → 3.1%, 40k users in 6 months.",
    thumbnail: "",
    heroImage: "",
    gallery: [],
    technologies: ["React", "PostgreSQL", "WebSockets", "Stripe"],
    client: "Orbital Labs",
    year: "2025",
    status: "published",
    featured: true,
    color: "#4DE3FF",
    stats: [
      { label: "Activation", value: "+86%" },
      { label: "Churn", value: "3.1%" },
      { label: "Users", value: "40k" },
    ],
    timeline: "12 weeks",
  },
  {
    title: "PULSE Festival — 3D Campaign",
    slug: "pulse-festival",
    category: "Digital Experience",
    tagline: "A WebGL universe for a music festival.",
    description:
      "Interactive lineup explorer with 3D stage, audio-reactive visuals and ticket flow. 1M visits in launch week.",
    challenge: "Lineup announcement was a static image. No hype, no shares, no ticket urgency.",
    idea: "Make the lineup a playable universe — fly through stages, preview artists, buy in two clicks.",
    design: "Neon brutalism, WebGL particles, scroll-driven camera, custom audio visualizer.",
    development: "Three.js + GSAP ScrollTrigger, headless CMS for artists, queue-based ticketing.",
    results: "1M visits week one, 34k shares, sold out in 48h. Awwwards honorable mention.",
    thumbnail: "",
    heroImage: "",
    gallery: [],
    technologies: ["Three.js", "GSAP", "WebGL", "Headless CMS"],
    client: "Pulse Live",
    year: "2026",
    status: "published",
    featured: true,
    color: "#7C5CFF",
    stats: [
      { label: "Visits", value: "1M" },
      { label: "Shares", value: "34k" },
      { label: "Sellout", value: "48h" },
    ],
    timeline: "6 weeks",
  },
];

export const NAV_LINKS = [
  { label: "Work", href: "/work" },
  { label: "Services", href: "/services" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];
