import byinksFoundation from "@/app/Projects Images/Byinks Foundation.png";
import cadrilTravels from "@/app/Projects Images/Cadril Travels.png";
import marvelTourism from "@/app/Projects Images/Marvel Tourism.png";
import paxxonAndCorbex from "@/app/Projects Images/Paxxon and Corbex.png";
import rightspec from "@/app/Projects Images/Rightspec.png";

export const SERVICES = [
  {
    id: "01",
    title: "WEB DEVELOPMENT",
    short: "Websites",
    desc: "Blazing-fast marketing sites & platforms. Next.js, headless CMS, edge rendering, 95+ Lighthouse.",
    tags: ["Next.js", "React", "Performance"],
    accent: "#D4FF3F",
    preview: "code",
  },
  {
    id: "02",
    title: "WEB APPLICATIONS",
    short: "Apps",
    desc: "Dashboards, SaaS, portals & internal tools. Postgres, auth, realtime, roles, billing.",
    tags: ["PostgreSQL", "Drizzle", "Auth"],
    accent: "#4DE3FF",
    preview: "app",
  },
  {
    id: "03",
    title: "UI / UX DESIGN",
    short: "Design",
    desc: "Research, wireframes, design systems & prototypes that convert visitors into customers.",
    tags: ["Figma", "Design Systems", "Motion"],
    accent: "#FF7AD9",
    preview: "design",
  },
  {
    id: "04",
    title: "E-COMMERCE",
    short: "Commerce",
    desc: "Headless storefronts with Stripe, inventory, CMS & CRO built-in. Built to sell.",
    tags: ["Stripe", "Headless", "CRO"],
    accent: "#FFB224",
    preview: "shop",
  },
  {
    id: "05",
    title: "DIGITAL EXPERIENCES",
    short: "3D / WebGL",
    desc: "Three.js, WebGL shaders, scroll cinema & interactive storytelling that people remember.",
    tags: ["Three.js", "GSAP", "Shaders"],
    accent: "#7C5CFF",
    preview: "3d",
  },
  {
    id: "06",
    title: "SEO & GROWTH",
    short: "Growth",
    desc: "Technical SEO, analytics, A/B testing & content engines that compound traffic.",
    tags: ["SEO", "Analytics", "Content"],
    accent: "#8AFF80",
    preview: "growth",
  },
];

export const PROCESS = [
  {
    id: "01",
    name: "DISCOVER",
    desc: "Workshops, audits, analytics & stakeholder interviews. We find the real problem before we design anything.",
    deliverables: ["Discovery workshop", "Tech audit", "User insights"],
    color: "#D4FF3F",
  },
  {
    id: "02",
    name: "CONCEPT",
    desc: "Information architecture, creative direction, motion language and prototype of the core journey.",
    deliverables: ["Sitemap", "Creative concept", "Clickable prototype"],
    color: "#4DE3FF",
  },
  {
    id: "03",
    name: "DESIGN",
    desc: "High-fidelity UI, design system, 3D & motion exploration. Every pixel earns its place.",
    deliverables: ["UI kit", "Design system", "Motion specs"],
    color: "#FF7AD9",
  },
  {
    id: "04",
    name: "DEVELOP",
    desc: "Clean code, CMS, integrations, animations & 3D. Reviewed, tested, performance-budgeted.",
    deliverables: ["Frontend + Backend", "CMS", "QA & perf pass"],
    color: "#7C5CFF",
  },
  {
    id: "05",
    name: "LAUNCH",
    desc: "Deploy, monitor, measure & iterate. SEO, analytics and growth loops from day one.",
    deliverables: ["Deploy & SSL", "Analytics", "30-day support"],
    color: "#FFB224",
  },
];

export const TECH_STACK = [
  "Next.js",
  "React",
  "TypeScript",
  "Three.js",
  "WebGL",
  "GSAP",
  "PostgreSQL",
  "Drizzle ORM",
  "Node.js",
  "PHP",
  "MySQL",
  "WordPress",
  "Tailwind",
  "Vercel",
  "Stripe",
  "Figma",
];

export const FALLBACK_PROJECTS = [
  {
    title: "Byinks Foundation",
    slug: "byinks-foundation",
    websiteUrl: "https://byinksfoundation.org",
    category: "Nonprofit Website",
    tagline: "A clear digital platform for empowering 10,000 widows.",
    description:
      "Byinks Foundation needed a warm, trustworthy online presence that could communicate its mission, mobilize volunteers and make donations feel immediate. We shaped the experience around its people and its 17th year of impact.",
    challenge:
      "The foundation's story and calls to action were difficult for visitors to find, especially on smaller screens.",
    idea: "Put the mission first: lead with real people, a memorable impact statement and direct paths to donate or volunteer.",
    design:
      "A people-first visual system with bold campaign typography, deep teal overlays and high-contrast action buttons.",
    development:
      "Responsive Next.js implementation with structured content sections, accessible navigation and conversion-focused donation and contact flows.",
    results:
      "A focused public-facing platform that makes the foundation's impact, programs and ways to help easy to understand.",
    thumbnail: byinksFoundation.src,
    heroImage: byinksFoundation.src,
    gallery: [],
    technologies: ["Next.js", "React", "Tailwind", "CMS"],
    client: "Byinks Foundation",
    year: "2026",
    status: "published",
    featured: true,
    color: "#4DE3FF",
    stats: [
      { label: "Mission", value: "10k" },
      { label: "Anniversary", value: "17th" },
      { label: "Focus", value: "Impact" },
    ],
    timeline: "6 weeks",
  },
  {
    title: "Cadril Travels",
    slug: "cadril-travels",
    websiteUrl: "https://cadriltravels.com/",
    category: "Travel Website",
    tagline: "A confident travel platform for tours, visas and global journeys.",
    description:
      "Cadril Travels needed a destination that could bring its travel management, MICE, visa and global jobs services together without losing the excitement of travel.",
    challenge:
      "Multiple travel services needed a simple information hierarchy so visitors could quickly choose the right next step.",
    idea: "Make the first impression feel like departure: pair an atmospheric destination image with clear, service-led navigation.",
    design: "Editorial travel imagery, strong display type and a calm blue palette that keeps the journey-oriented content easy to scan.",
    development: "Responsive Next.js build with structured service pages, consultation calls to action and navigation prepared for future booking flows.",
    results: "A polished travel experience that gives tours, visa, flight, study and government services a unified digital home.",
    thumbnail: cadrilTravels.src,
    heroImage: cadrilTravels.src,
    gallery: [],
    technologies: ["Next.js", "React", "SEO", "CMS"],
    client: "Cadril Travels",
    year: "2026",
    status: "published",
    featured: true,
    color: "#4DE3FF",
    stats: [
      { label: "Services", value: "08" },
      { label: "Audience", value: "Global" },
      { label: "Journey", value: "Clear" },
    ],
    timeline: "7 weeks",
  },
  {
    title: "Rightspec",
    slug: "rightspec",
    websiteUrl: "https://rightspec.com.ng",
    category: "Digital Agency Website",
    tagline: "A full-lifecycle digital agency site built to start better projects.",
    description:
      "Rightspec needed to communicate a broad range of capabilities while keeping the path to a new project obvious.",
    challenge: "Services, process and portfolio content had to feel substantial without overwhelming prospective clients.",
    idea: "Turn the agency offer into a visual system: clear service pillars, confident proof and one consistent route to contact.",
    design: "Bright editorial layouts with navy type, orange highlights, generous spacing and crisp service-focused content blocks.",
    development: "Responsive Next.js build with reusable content sections, accessible interaction states and a scalable portfolio structure.",
    results: "A sharper agency presence that explains the full lifecycle of the work and gives visitors a confident way to start.",
    thumbnail: rightspec.src,
    heroImage: rightspec.src,
    gallery: [],
    technologies: ["Next.js", "React", "UI/UX", "SEO"],
    client: "Rightspec",
    year: "2026",
    status: "published",
    featured: true,
    color: "#FFB224",
    stats: [
      { label: "Pillars", value: "05" },
      { label: "Approach", value: "Full" },
      { label: "CTA", value: "Clear" },
    ],
    timeline: "5 weeks",
  },
  {
    title: "Marvel Tourism",
    slug: "marvel-tourism",
    websiteUrl: "https://marvel-tourism-blue.vercel.app/",
    category: "Travel Website",
    tagline: "A polished travel experience for unforgettable journeys.",
    description: "Marvel Tourism needed a modern travel platform that could showcase destinations, packages and a more direct route to booking.",
    challenge: "Travel offers needed to feel inspiring while keeping essential booking information easy to find.",
    idea: "Use the destination itself as the invitation: cinematic imagery, confident typography and clear paths to explore.",
    design: "Ocean blues, generous editorial type and resort imagery create a premium travel-first experience.",
    development: "Responsive Next.js implementation with destination-led content, package discovery and prominent booking actions.",
    results: "A more memorable digital storefront for travel packages, destinations and direct enquiries.",
    thumbnail: marvelTourism.src,
    heroImage: marvelTourism.src,
    gallery: [],
    technologies: ["Next.js", "React", "SEO", "CMS"],
    client: "Marvel Tourism",
    year: "2026",
    status: "published",
    featured: true,
    color: "#4DE3FF",
    stats: [
      { label: "Focus", value: "Travel" },
      { label: "Booking", value: "Direct" },
      { label: "Reach", value: "Global" },
    ],
    timeline: "6 weeks",
  },
  {
    title: "Sky Orchestra Music",
    slug: "sky-orchestra-music",
    websiteUrl: "https://skyorchestra.com.ng/",
    category: "Music Website",
    tagline: "A digital stage for sound, artists and live experiences.",
    description: "Sky Orchestra Music needed a distinctive platform for presenting its sound, identity and next audience-facing experience.",
    challenge: "The brand needed a digital presence with enough atmosphere to match its music without sacrificing clarity.",
    idea: "Treat the website like a stage: establish mood first, then guide visitors toward the music and the next event.",
    design: "Expressive editorial direction, immersive imagery and a bold visual rhythm shaped around performance.",
    development: "Responsive Next.js experience with flexible content sections for music, artists, events and enquiries.",
    results: "A focused online home that gives the music brand room to build an audience and share what is next.",
    thumbnail: "",
    heroImage: "",
    gallery: [],
    technologies: ["Next.js", "React", "UI/UX", "CMS"],
    client: "Sky Orchestra Music",
    year: "2026",
    status: "published",
    featured: true,
    color: "#7C5CFF",
    stats: [
      { label: "Format", value: "Music" },
      { label: "Stage", value: "Digital" },
      { label: "Mood", value: "Live" },
    ],
    timeline: "5 weeks",
  },
  {
    title: "Paxxon and Corbex",
    slug: "paxxon-and-corbex",
    websiteUrl: "https://paxxoncorbex.com/",
    category: "Corporate Website",
    tagline: "A stronger digital presence for connected business ecosystems.",
    description: "Paxxon and Corbex needed a corporate experience that could make its business infrastructure, services and opportunities feel clear and credible.",
    challenge: "A broad business offer had to be presented with enough authority for partners while remaining easy for new visitors to navigate.",
    idea: "Lead with connection: unify industries, services and enquiries under one confident digital language.",
    design: "Deep burgundy, warm gold and architectural imagery create a premium corporate identity with a strong sense of place.",
    development: "Responsive Next.js build with modular service content, clear enquiry paths and a scalable corporate information structure.",
    results: "A more assured platform for communicating capabilities, opportunities and the next business conversation.",
    thumbnail: paxxonAndCorbex.src,
    heroImage: paxxonAndCorbex.src,
    gallery: [],
    technologies: ["Next.js", "React", "SEO", "CMS"],
    client: "Paxxon and Corbex",
    year: "2026",
    status: "published",
    featured: true,
    color: "#FFB224",
    stats: [
      { label: "Positioning", value: "Clear" },
      { label: "Market", value: "Global" },
      { label: "Offer", value: "Connected" },
    ],
    timeline: "7 weeks",
  },
];

export const NAV_LINKS = [
  { label: "Work", href: "/work" },
  { label: "Services", href: "/services" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];
